[package]
name = "generator-mavlink-plan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.166", features = ["derive"] }
serde_json = "1.0.107"
serde_repr = "0.1.16"
reqwest = { version = "0.11", features = ["json", "blocking"] }
