version: '2.19'

services:
  build-for-20.04:
    image: generator-mavlink-plan:20.04
    build:
      context: .
      dockerfile: compile.20.04.Dockerfile
    working_dir: /home/generator-mavlink-plan/
    volumes:
      - ${PWD}/generated-executables:/home/generator-mavlink-plan/generated-executables:rw
    command: >
      /bin/bash -c "cargo add proj@0.14;
                    cargo build --release;
                    cp ./target/release/generator-mavlink-plan ./generated-executables/flight-route-planner-20"

  build-for-22.04:
    image: generator-mavlink-plan:22.04
    build:
      context: .
      dockerfile: compile.22.04.Dockerfile
    working_dir: /home/generator-mavlink-plan/
    volumes:
      - ${PWD}/generated-executables:/home/generator-mavlink-plan/generated-executables:rw
    command: >
      /bin/bash -c "cargo add proj@0.25;
                    cargo build --release
                    cp ./target/release/generator-mavlink-plan ./generated-executables/flight-route-planner-22"
